In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("Accounting.csv")
df.head()

,gvkey,Date,Company Name,Fiscal Year,Total Current Assets,Total Assets,Total Long-Term Debt,Accumulated Depreciation,Total Current Liabilities,Gross Property Plant and Equipment,Total Receivables,Total Trade Receivables,COGS,Net Income,Total Revenue,Advertising Expense,R&D Expense,SG&A Expense,Net Cash Flow from Operations
0,6266,12/31/1980,JOHNSON & JOHNSON,12,1971.000,3342.501,70.1,614.6,773.5,1776.5,643.8,643.8,2288.400,400.7,4837.379,233.5,232.8,1794.2,NaN
1,6266,12/31/1981,JOHNSON & JOHNSON,12,2202.200,3820.400,91.7,678.0,881.2,2013.6,705.9,705.9,2498.901,467.6,5399.000,270.6,282.9,2030.6,NaN
2,6266,12/31/1982,JOHNSON & JOHNSON,12,2253.101,4209.570,142.2,733.5,900.2,2311.4,758.1,758.1,2274.701,473.4,5760.871,307.7,363.2,2612.0,NaN
3,6266,12/31/1983,JOHNSON & JOHNSON,12,2457.101,4461.496,195.6,801.5,923.8,2469.7,836.4,836.4,2262.000,489.0,5972.871,301.7,405.1,2758.0,NaN
4,6266,12/31/1984,JOHNSON & JOHNSON,12,2513.699,4541.371,224.8,898.7,1042.4,2619.3,877.3,877.3,2243.099,514.5,6124.496,336.6,421.2,2909.6,NaN

In [6]:
df.describe()

,gvkey,Fiscal Year,Total Current Assets,Total Assets,Total Long-Term Debt,Accumulated Depreciation,Total Current Liabilities,Gross Property Plant and Equipment,Total Receivables,Total Trade Receivables,COGS,Net Income,Total Revenue,Advertising Expense,R&D Expense,SG&A Expense,Net Cash Flow from Operations
count,6694.000000,6694.000000,6274.000000,6291.000000,6266.000000,6065.000000,6280.000000,6064.000000,6213.000000,6155.000000,6273.000000,6273.000000,6273.000000,1190.000000,5828.000000,4028.000000,6249.000000
mean,151741.458470,10.678369,711.036513,2120.656475,347.547273,276.596143,421.734283,579.377693,196.292643,170.558070,278.528460,140.814934,1006.177569,92.132316,193.977190,689.984625,219.049244
std,47774.554369,2.742947,4220.086109,13883.228463,2419.181874,1936.348410,2892.825165,3776.432954,1237.458603,1102.003381,1671.292103,1316.413914,6453.205713,398.110377,1163.103975,3439.165810,1671.835481
min,6266.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.092000,-4887.218000,-3.937000,0.000000,-16.921000,-9.679000,-770.745000
25%,127481.000000,12.000000,6.264250,10.300500,0.000000,0.296000,2.479250,0.718500,0.023000,0.000000,0.116000,-29.773000,0.016000,0.106500,2.855750,5.616250,-21.260000
50%,157234.000000,12.000000,30.631000,43.488000,0.344000,2.259000,8.105000,5.401000,0.922000,0.360000,10.389000,-9.823000,4.738000,1.300000,12.458000,18.598500,-6.006000
75%,178097.000000,12.000000,110.183500,155.175000,10.786500,10.918000,28.517000,24.142000,7.437000,5.750000,45.528000,-1.280000,42.403000,10.614000,40.954000,71.236500,-0.230000
max,278308.000000,12.000000,65032.000000,187378.000000,41710.041000,29450.000000,55802.000000,50353.000000,16160.000000,16160.000000,31853.600000,35153.000000,94943.000000,2900.000000,30531.000000,39887.000000,24266.000000

In [7]:
df.columns

Index(['gvkey', 'Date', 'Company Name', 'Fiscal Year', 'Total Current Assets',
       'Total Assets', 'Total Long-Term Debt', 'Accumulated Depreciation',
       'Total Current Liabilities', 'Gross Property Plant and Equipment',
       'Total Receivables', 'Total Trade Receivables', 'COGS', 'Net Income',
       'Total Revenue', 'Advertising Expense', 'R&D Expense', 'SG&A Expense',
       'Net Cash Flow from Operations'],
      dtype='object')

In [8]:
df.shape

(6694, 19)

In [9]:
df.isna().sum()

gvkey                                    0
Date                                     0
Company Name                             0
Fiscal Year                              0
Total Current Assets                   420
Total Assets                           403
Total Long-Term Debt                   428
Accumulated Depreciation               629
Total Current Liabilities              414
Gross Property Plant and Equipment     630
Total Receivables                      481
Total Trade Receivables                539
COGS                                   421
Net Income                             421
Total Revenue                          421
Advertising Expense                   5504
R&D Expense                            866
SG&A Expense                          2666
Net Cash Flow from Operations          445
dtype: int64